"use strict";

const asset = "assets/img/";
const projects = {
  stylesense: { domain:"Fashion Retail", title:"StyleSense Analytics", type:"Excel Business Intelligence", thumbnail:"portfolio project info/01_StyleSense Analytics/01_thumbnail.PNG", dashboard:"portfolio project info/01_StyleSense Analytics/StyleSense_Readme_Collage.png", github:"https://github.com/TNamrathaPadiyar/stylesense-Fashion-retail-analytics-excel", report:"portfolio project info/01_StyleSense Analytics/StyleSense_Portfolio_Executive_Report.pdf", skills:["Power Query Data Transformation","Relational Data Modeling (Power Pivot)","DAX KPI Development","Retail Business Analytics","Inventory & Merchandising Analysis"], tools:["Microsoft Excel.png","GitHub.png"], description:"Developed an end-to-end retail analytics solution by transforming six disconnected business datasets into a centralized Excel BI model, enabling inventory, merchandising, seasonal demand, and promotional performance analysis.", overview:"Designed an end-to-end retail analytics solution that unified sales, inventory, customer, supplier, store, and promotion data into a centralized analytical model. The project demonstrates how advanced Excel can be used as a Business Intelligence platform to support strategic retail decision-making.", problem:"Retail data was scattered across multiple operational datasets, making it difficult to understand inventory risks, seasonal demand, promotional performance, and merchandising effectiveness. The objective was to build a single analytical solution that transformed fragmented data into meaningful business intelligence.", insights:["Identified high-revenue product categories operating with low inventory, highlighting potential stock-out risks.","Discovered seasonal demand patterns to improve inventory and workforce planning.","Evaluated promotional campaigns to identify the marketing strategies driving the highest revenue.","Revealed product performance variations across fashion seasons to support merchandising decisions."], recommendations:["Prioritize inventory replenishment for high-performing categories before stock shortages occur.","Align inventory planning with seasonal purchasing trends to reduce excess and shortage.","Increase investment in promotional campaigns with proven business impact.","Use centralized KPI reporting to support faster, data-driven retail decisions."] },
  delivery: { domain:"Logistics", title:"The Last Mile Challenge", type:"SQL & Python Operational Analytics", thumbnail:"portfolio project info/02_Delivery Operational Analytics/02_thumbnail.PNG", dashboard:"portfolio project info/02_Delivery Operational Analytics/delivery operational analystics visuals collage.png", github:"https://github.com/TNamrathaPadiyar/the-last-mile-challenge", report:"portfolio project info/02_Delivery Operational Analytics/Delivery case Study Executive Insights Report.pdf", skills:["SQL Business Analysis","Data Quality Validation","Logistics Performance Analytics","Exploratory Data Analysis (Python)","Operational KPI Analysis","Business Insight Generation"], tools:["SQL.png","Python.png","Pandas.png","Matplotlib.png","GitHub.png"], description:"Investigated logistics operations using SQL and Python to identify delivery bottlenecks, operational risks, and performance improvement opportunities across nearly 10,000 shipment records.", overview:"Analyzed shipment operations to uncover the operational drivers behind delivery delays. Combined SQL-based business analysis with Python visualizations to transform logistics data into actionable insights for operational decision-making.", problem:"Delivery delays were affecting operational efficiency and customer experience, but the underlying causes were unclear. The project investigated courier performance, regional bottlenecks, shipment characteristics, and seasonal trends to identify the highest-impact operational issues.", insights:["Delivery delays were driven by multiple operational factors rather than a single courier partner.","High shipment volume combined with elevated delays created greater business impact than delay averages alone.","Seasonal workload significantly influenced delivery performance during peak operational months.","Product category and shipment characteristics revealed hidden operational bottlenecks."], recommendations:["Focus improvement efforts on high-volume operational regions with recurring delivery delays.","Strengthen workforce and logistics planning before seasonal demand peaks.","Continuously monitor high-impact product categories to reduce service failures.","Evaluate operational performance using multiple KPIs instead of relying on a single metric."] },
  adoption: { domain:"Non-Profit Operations", title:"Rescue to Adoption", type:"SQL & Power BI Business Intelligence", thumbnail:"portfolio project info/04_From Rescue to Adoption_project/04_thumbnail.PNG", dashboard:"portfolio project info/04_From Rescue to Adoption_project/from_rescue_to_adoption_dashboard.png", github:"https://github.com/TNamrathaPadiyar/rescue-to-adoption-executive-analytics", report:"portfolio project info/04_From Rescue to Adoption_project/Executive_Project_Report_Rescue_to_Adoption.pdf", skills:["SQL Analytics (CTEs & Window Functions)","Power BI Dashboard Development","Relational Data Modeling","Executive KPI Reporting","Business Intelligence & Storytelling","Data Cleaning & Transformation"], tools:["SQL.png","Power BI.png","MySQL.png","GitHub.png"], description:"Built an end-to-end Business Intelligence solution using SQL and Power BI to monitor animal rescue operations, adoption performance, healthcare expenditure, and executive KPIs through interactive dashboards.", overview:"Developed an executive-level Business Intelligence solution that transformed operational rescue and adoption data into interactive dashboards for monitoring adoption performance, healthcare expenditure, breed performance, and operational efficiency. The project integrated SQL analytics with Power BI to support data-driven decision-making.", problem:"Animal welfare organizations collect large volumes of operational data, but disconnected datasets make it difficult to monitor adoption rates, healthcare investments, resource utilization, and operational performance. This project centralized the data into a single executive reporting solution.", insights:["Identified breeds contributing disproportionately to medical expenditure using Pareto analysis.","Compared healthcare investment against adoption outcomes to evaluate operational efficiency.","Highlighted cities and breeds requiring additional management attention.","Standardized executive KPIs to improve organizational performance monitoring."], recommendations:["Prioritize operational improvements for low-performing breeds.","Optimize healthcare spending by focusing on high-cost resource drivers.","Monitor executive KPIs regularly to support proactive decision-making.","Expand analytical reporting for continuous operational improvement."] },
  telecom: { domain:"Telecommunications", title:"Telecom Customer Churn Investigation", type:"Python Exploratory Analysis", thumbnail:"portfolio project info/05_Telecom Customer Churn Analysis/05_thumbnail.PNG", dashboard:"portfolio project info/05_Telecom Customer Churn Analysis/telecom_churn_dashboard_collage_compact.png", github:"https://github.com/TNamrathaPadiyar/Telecom-Churn-Project", report:"portfolio project info/05_Telecom Customer Churn Analysis/Telecom_Churn_Analysis_Report.pdf", skills:["Python Exploratory Data Analysis (EDA)","Data Cleaning & Validation","Customer Behavior Analytics","Business Insight Generation","Data Visualization (Matplotlib)","Customer Retention Analysis"], tools:["Python.png","Pandas.png","NumPy.png","Matplotlib.png","Seaborn.png","GitHub.png"], description:"Performed exploratory data analysis using Python to uncover customer churn patterns, enabling telecom businesses to understand retention risks and support data-driven customer engagement strategies.", overview:"Conducted an exploratory analysis of over 7,000 telecom customer records to investigate churn behavior across customer demographics, tenure, pricing, and contract types. The project transformed raw customer data into actionable business insights through Python-based analysis and visualization.", problem:"Customer churn directly impacts recurring revenue and customer lifetime value. The objective was to identify behavioral and service-related characteristics associated with customer attrition, helping businesses design more effective retention strategies.", insights:["Customers on month-to-month contracts exhibited significantly higher churn.","Short-tenure customers were more likely to discontinue services.","Monthly charges showed a relationship with customer retention behavior.","Demographic factors such as gender had minimal influence compared to contractual and service-related characteristics."], recommendations:["Encourage customers to migrate to longer-term contracts through loyalty incentives.","Improve onboarding and engagement during the early customer lifecycle.","Review pricing strategies to strengthen perceived customer value.","Continuously monitor churn as a strategic business KPI and support future predictive analytics initiatives."] },
  retail: { domain:"Retail Operations", title:"Retail Intelligence Dashboard", type:"Excel Business Intelligence", thumbnail:"portfolio project info/06_Retail Business Health Dashboard/06_thumbnail.PNG", dashboard:"portfolio project info/06_Retail Business Health Dashboard/dashboard.png", github:"https://github.com/TNamrathaPadiyar/Unlocking-Retail-Performance-Profit-Risk-Customer-Behavior-Insights", report:"portfolio project info/06_Retail Business Health Dashboard/Retail_health_Executive_Analysis_Report.pdf", skills:["Advanced Microsoft Excel","Interactive Dashboard Development","Pivot Tables & Pivot Charts","KPI Design & Business Reporting","Data Cleaning & Feature Engineering","Customer & Profitability Analytics"], tools:["Microsoft Excel.png","GitHub.png"], description:"Designed an interactive Microsoft Excel Business Intelligence dashboard to analyze retail profitability, customer behavior, cancellation patterns, and operational efficiency through executive-level reporting.", overview:"Developed an executive-level Retail Intelligence Dashboard that transformed raw retail transaction data into meaningful business insights. The project integrated profitability analysis, customer behavior, operational efficiency, and interactive reporting using Microsoft Excel.", problem:"Retail organizations generate large volumes of transactional data, but raw sales reports alone cannot explain profitability, customer purchasing behavior, cancellation trends, or operational efficiency. This project converted retail transactions into actionable business intelligence.", insights:["Technology emerged as the highest-performing and most profitable product category.","Profitability declined significantly when discounts exceeded approximately 30%.","Post-shipment cancellations contributed to higher operational losses than pre-shipment cancellations.","Internal operational processes had greater influence on delays than delivery distance."], recommendations:["Prioritize high-performing Technology products while improving Furniture profitability.","Establish approval controls for discounts above 30% to protect profit margins.","Reduce post-shipment cancellations through improved order validation and operational processes.","Continuously monitor delivery KPIs and operational efficiency using interactive dashboards."] },
  workforce: { domain:"Human Resources", title:"Learning to Lead: Workforce Learning Intelligence", type:"Python Workforce Analytics", thumbnail:"portfolio project info/07_Employee_Training_Workforce_Analytics/07_thumbnail.PNG", dashboard:"portfolio project info/07_Employee_Training_Workforce_Analytics/workforce_visuals_collage.png", github:"https://github.com/TNamrathaPadiyar/learning-to-lead-workforce-analytics", report:"portfolio project info/07_Employee_Training_Workforce_Analytics/workforce_Executive_Summary_and_Recommendations.pdf", skills:["Python Exploratory Data Analysis","HR & Workforce Analytics","Data Cleaning & Feature Engineering","Business Reporting & Storytelling","Data Visualization (Matplotlib & Seaborn)","Learning Effectiveness Analysis"], tools:["Python.png","Pandas.png","NumPy.png","Matplotlib.png","Seaborn.png","GitHub.png"], description:"Developed a Python-based workforce analytics solution to evaluate employee learning participation, training effectiveness, and organizational performance for HR and Learning & Development teams.", overview:"Designed a structured workforce analytics workflow that transformed employee, training, and performance data into actionable business intelligence. The project integrated data profiling, cleaning, feature engineering, exploratory analysis, and business-focused reporting.", problem:"Organizations invest heavily in employee training but often lack structured reporting to evaluate participation, completion behavior, and measurable performance improvements. This project addressed that gap with a reproducible analytics solution.", insights:["Learning participation varied across departments and employee experience levels.","Training completion rates remained generally consistent across organizational departments.","Completion duration analysis indicated stable learning delivery timelines across programs.","Completion rates and post-training performance provided a more balanced measure of training effectiveness than participation alone."], recommendations:["Develop experience-specific learning pathways for different workforce segments.","Monitor departmental participation and completion trends through periodic reporting.","Prioritize learning programs demonstrating both high completion and measurable performance improvement.","Continue tracking workforce learning KPIs to support long-term organizational development."] }
};

const navMenu = document.querySelector(".nav-links"), hamburger = document.querySelector(".hamburger"), navbar = document.querySelector(".navbar");
hamburger.addEventListener("click", () => { const open = navMenu.classList.toggle("show"); hamburger.setAttribute("aria-expanded", open); });
document.querySelectorAll(".nav-links a").forEach(a => a.addEventListener("click", () => navMenu.classList.remove("show")));
window.addEventListener("scroll", () => navbar.classList.toggle("scrolled", window.scrollY > 60));

const grid = document.querySelector("#projects-grid");
grid.innerHTML = Object.entries(projects).map(([id,p]) => `<article class="project-card" data-project="${id}" tabindex="0" role="button" aria-label="Open ${p.title}"><div class="project-thumbnail"><img src="${p.thumbnail}" alt="${p.title} project thumbnail"></div><div class="project-content"><span class="project-domain">${p.domain}</span><h3>${p.title}</h3><p>${p.description}</p><div class="project-tools">${p.tools.slice(0,4).map(t=>`<img src="${asset+t}" alt="">`).join("")}</div><span class="view-project">View project details →</span></div></article>`).join("");

const projectModal=document.querySelector("#project-modal"), closeProjectButton=document.querySelector(".modal-close");
const setText=(id,value)=>document.querySelector(id).textContent=value;
function iconList(selector, items, tags=false){ document.querySelector(selector).innerHTML=tags ? items.map(x=>`<span class="skill-tag">${x}</span>`).join("") : items.map(x=>`<img src="${asset+x}" alt="${x.replace(/\.[^.]+$/,"")}">`).join(""); }
function list(selector, items){ document.querySelector(selector).innerHTML=items.map(x=>`<li>${x}</li>`).join(""); }
function openProject(id){ const p=projects[id]; if(!p) return; setText("#modal-title",p.title); setText("#modal-domain",p.domain); setText("#modal-type",p.type); setText("#modal-overview",p.overview); setText("#modal-problem",p.problem); list("#modal-insights",p.insights); list("#modal-recommendations",p.recommendations); iconList("#modal-skills",p.skills,true); iconList("#modal-tools",p.tools); const image=document.querySelector("#modal-dashboard"); image.src=p.dashboard; image.alt=`${p.title} project visual`; document.querySelector("#modal-github").href=p.github; document.querySelector("#modal-report").href=p.report; document.querySelector("#modal-download").href=p.report; projectModal.classList.add("active"); document.body.classList.add("modal-open"); }
function closeProject(){projectModal.classList.remove("active"); document.body.classList.remove("modal-open");}
grid.addEventListener("click", e=>{const card=e.target.closest(".project-card"); if(card) openProject(card.dataset.project);});
grid.addEventListener("keydown", e=>{if((e.key==="Enter"||e.key===" ")&&e.target.classList.contains("project-card")){e.preventDefault();openProject(e.target.dataset.project);}});
closeProjectButton.addEventListener("click",closeProject); document.querySelector(".modal-overlay").addEventListener("click",closeProject);

const documentModal=document.querySelector("#document-modal"), documentFrame=document.querySelector("#document-frame");
function openDocument(url){documentFrame.src=url;documentModal.classList.add("active");document.body.classList.add("modal-open");}
function closeDocument(){documentModal.classList.remove("active");documentFrame.src="";document.body.classList.remove("modal-open");}
document.querySelector("#modal-report").addEventListener("click",e=>{e.preventDefault();openDocument(e.currentTarget.href);});
document.querySelector(".document-close").addEventListener("click",closeDocument);document.querySelector(".document-overlay").addEventListener("click",closeDocument);

document.querySelector(".copy-email").addEventListener("click", async e=>{const button=e.currentTarget;try {await navigator.clipboard.writeText(button.dataset.email);button.setAttribute("title","Copied!");button.classList.add("copied");setTimeout(()=>{button.setAttribute("title","Copy email address");button.classList.remove("copied");},1800);} catch {button.setAttribute("title","Copy failed");}});
const certificates={
  ibm:{title:"IBM SkillsBuild – Data Fundamentals",provider:"IBM SkillsBuild",image:"assets/certificates/ibm.png",file:"certification and course/ibm.pdf",learning:["Built a solid understanding of core data concepts including data types, data lifecycle, data ethics, and the role of data in business decision-making.","Established the theoretical foundation required for analytics, reporting, and business intelligence, strengthening the ability to approach data-driven problems systematically."]},
  deloitte:{title:"Deloitte Data Analytics Job Simulation",provider:"Deloitte · Forage",image:"assets/certificates/deloitte.png",file:"certification and course/deloitte.pdf",learning:["Applied analytical thinking to realistic business scenarios involving data analysis and forensic technology through practical tasks rather than theoretical exercises.","Strengthened problem-solving, structured investigation, and professional reporting skills by working on business-oriented analytics challenges similar to those encountered in consulting environments."]},
  quantium:{title:"Quantium Data Analytics Job Simulation",provider:"Quantium · Forage",image:"assets/certificates/quantium.png",file:"certification and course/Quantium_Certificate.pdf",learning:["Worked through an end-to-end retail analytics simulation covering customer analytics, data preparation, experimentation, uplift testing, and commercial decision-making.","Developed practical experience in translating analytical findings into business recommendations, using data to evaluate customer behaviour and measure the impact of business initiatives."]},
  hp:{title:"HP LIFE – Presenting Data",provider:"HP LIFE",image:"assets/certificates/hp.png",file:"certification and course/Presenting Data_hplife_Certificate.pdf",learning:["Learned how to select appropriate charts, communicate analytical findings clearly, and present business insights through effective data visualization.","Improved the ability to transform complex analytical results into concise, decision-focused presentations for business stakeholders."]}
};
const certificateModal=document.querySelector("#certificate-modal");
function closeCertificate(){certificateModal.classList.remove("active");document.body.classList.remove("modal-open");}
function openCertificate(id){const c=certificates[id];if(!c)return;document.querySelector("#certificate-preview").src=c.image;setText("#certificate-title",c.title);setText("#certificate-provider",c.provider);setText("#certificate-overview","Professional learning and practical analytical capabilities gained.");list("#certificate-skills-list",c.learning);const view=document.querySelector("#view-certificate");view.href=c.file;view.onclick=e=>{e.preventDefault();openDocument(c.file);};certificateModal.classList.add("active");document.body.classList.add("modal-open");}
document.querySelectorAll(".certificate-card").forEach(card=>{card.tabIndex=0;card.setAttribute("role","button");const open=()=>openCertificate(card.dataset.certificate);card.addEventListener("click",open);card.addEventListener("keydown",e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();open();}});});
document.querySelector(".certificate-close").addEventListener("click",closeCertificate);document.querySelector(".certificate-overlay").addEventListener("click",closeCertificate);
document.querySelectorAll(".document-link").forEach(link=>link.addEventListener("click",e=>{e.preventDefault();openDocument(link.href);}));
document.addEventListener("keydown",e=>{if(e.key==="Escape"){closeProject();closeDocument();closeCertificate();navMenu.classList.remove("show");}});
